#!/bin/sh

PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_ENDPOINT -U $POSTGRES_USER -c \
  "CREATE DATABASE IF NOT EXISTS ${POSTGRES_DB} ENCODING 'UTF8';";

PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_ENDPOINT -U $POSTGRES_USER -d $POSTGRES_DB -c \
  "GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER}";

alembic upgrade head